### ISSUE TITLE
Support skylark + operator for dicts

### ISSUE THREAD

**Issue by benley** [bazelbuild/skydoc#10]
Skylark has the + operator defined for merging dicts, but this currently breaks skydoc:

``` py
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_bstaffin/fe5f64f9e55476a949b9dc1d4a94e1b8/execroot/bazel_rules_pex/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_rules_pex/../io_bazel_skydoc/skydoc/main.py", line 245, in <module>
    main(FLAGS(sys.argv))
  File "/private/var/tmp/_bazel_bstaffin/fe5f64f9e55476a949b9dc1d4a94e1b8/execroot/bazel_rules_pex/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_rules_pex/../io_bazel_skydoc/skydoc/main.py", line 224, in main
    rule_doc_extractor.parse_bzl(bzl_file)
  File "/private/var/tmp/_bazel_bstaffin/fe5f64f9e55476a949b9dc1d4a94e1b8/execroot/bazel_rules_pex/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/rule_extractor.py", line 179, in parse_bzl
    self._process_skylark(bzl_file)
  File "/private/var/tmp/_bazel_bstaffin/fe5f64f9e55476a949b9dc1d4a94e1b8/execroot/bazel_rules_pex/bazel-out/host/bin/external/io_bazel_skydoc/skydoc/skydoc.runfiles/io_bazel_skydoc/skydoc/rule_extractor.py", line 65, in _process_skylark
    exec(compiled) in SKYLARK_STUBS, skylark_locals
  File "pex/pex_rules.bzl", line 249, in <module>
    executable = True,
TypeError: unsupported operand type(s) for +: 'dict' and 'dict'
```

The bazel docs suggest using `dict(a.items() + b.items())` as a workaround, so this isn't disastrous, but it would be nice if it just worked :-)

**Comment by damienmg** [comment]
IMHO `+` should just not be supported in skylark if it is not supported in python

**Comment by benley** [comment]
That also sounds reasonable, albeit a breaking change.

For what it's worth, giving dict an __add__ method in python has been considered and rejected upstream: http://bugs.python.org/issue6410
